apiVersion: v1
kind: Service
metadata:
  labels:
    app: meu-nginx
  name: meu-nginx
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - nodePort: 30425
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: meu-nginx
  sessionAffinity: None
  type: LoadBalancer
